project:
  type: website
  output-dir: docs
  render:
    - index.qmd

website:
  title: "FBMFOR — Food Fraud Analysis"
  navbar:
    background: "#003366"
    foreground: "#ffffff"
    left:
      - href: index.qmd
        text: Home
      - text: Open in Colab
        href: https://colab.research.google.com/github/ggkuhnle/fbmfor-foodfraud/blob/main/notebooks/FBMFOR_Chemometrics_Analysis.ipynb
        target: _blank
    right:
      - icon: github
        href: https://github.com/ggkuhnle/fbmfor-foodfraud
        target: _blank
  page-footer:
    center: "FBMFOR — Food Fraud Analysis | University of Reading | 2025/2026"

format:
  html:
    theme:
      light: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
